# Generated by Django 6.0.3 on 2026-03-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_equipment_project_technologytag_userprofile_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="permissions",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_name", models.CharField(max_length=100)),
                ("feature_action", models.CharField(max_length=100)),
                (
                    "bit_position",
                    models.PositiveIntegerField(editable=False, unique=True),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "unique_together": {("module_name", "feature_action")},
            },
        ),
    ]
