# Generated by Django 6.0.3 on 2026-03-22 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_role_permissions_role_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("onboarding", "Onboarding"),
                            ("offboarding", "Offboarding"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklist Template",
                "verbose_name_plural": "Checklist Templates",
            },
        ),
        migrations.CreateModel(
            name="ChecklistInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "In Progress"), ("done", "Done")],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_instances",
                        to="core.userprofile",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="core.checklisttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklist Instance",
                "verbose_name_plural": "Checklist Instances",
            },
        ),
        migrations.CreateModel(
            name="TaskTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "role_responsible",
                    models.CharField(
                        choices=[("HR", "HR"), ("IT", "IT"), ("Manager", "Manager")],
                        default="HR",
                        max_length=20,
                    ),
                ),
                (
                    "checklist_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_templates",
                        to="core.checklisttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Template",
                "verbose_name_plural": "Task Templates",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to="core.userprofile",
                    ),
                ),
                (
                    "checklist_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="core.checklistinstance",
                    ),
                ),
                (
                    "task_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklist_tasks",
                        to="core.tasktemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklist Task",
                "verbose_name_plural": "Checklist Tasks",
            },
        ),
    ]
