# Generated by Django 6.0.3 on 2026-03-19 16:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_role_permissions_role_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_id",
                    models.CharField(
                        help_text="Unique identifier for the asset",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Asset name/type", max_length=200)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("damaged", "Damaged"),
                        ],
                        default="good",
                        help_text="Current condition of the asset",
                        max_length=20,
                    ),
                ),
                (
                    "warranty_until",
                    models.DateField(
                        blank=True, help_text="Warranty expiration date", null=True
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(help_text="Date when the asset was purchased"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("lost", "Lost"),
                            ("returned", "Returned"),
                            ("damaged", "Damaged"),
                        ],
                        default="active",
                        help_text="Current status of the asset",
                        max_length=20,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Manufacturer serial number",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, help_text="Asset model", max_length=100, null=True
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True,
                        help_text="Asset manufacturer",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Purchase price of the asset",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional description or notes",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the asset was assigned"
                    ),
                ),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the asset was returned (optional)",
                        null=True,
                    ),
                ),
                (
                    "return_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("damaged", "Damaged"),
                        ],
                        help_text="Condition when returned",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the assignment",
                        null=True,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset being assigned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.asset",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who made the assignment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments_made",
                        to="core.userprofile",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee receiving the asset",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_assignments",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="ReplacementLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for replacement")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the replacement occurred"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost of replacement",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset that was replaced",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replacement_logs",
                        to="core.asset",
                    ),
                ),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who performed the replacement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replacements_made",
                        to="core.userprofile",
                    ),
                ),
                (
                    "replacement_asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="New asset that replaced this one",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaced_assets",
                        to="core.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Replacement Log",
                "verbose_name_plural": "Replacement Logs",
                "ordering": ["-date"],
            },
        ),
    ]
