# Generated by Django 6.0.3 on 2026-03-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_employee_profile_schema"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "Employee Profile",
                "verbose_name_plural": "Employee Profiles",
            },
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_active",
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
