# Generated by Django 6.0.3 on 2026-03-18 21:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.user_avatar_upload_to
            ),
        ),
    ]
