# Generated by Django 6.0.3 on 2026-03-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="permissions",
            field=models.CharField(default="", max_length=255),
        ),
    ]
