# Generated by Django 6.0.3 on 2026-03-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_userprofile_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
