# Generated by Django 6.0.3 on 2026-03-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_checklisttemplate_checklistinstance_tasktemplate_and_more"),
        ("core", "0010_add_avatar_url_to_userprofile"),
    ]

    operations = []
