# Generated by Django 6.0.3 on 2026-03-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_asset_assignment_replacementlog"),
        ("core", "0011_merge_20260324_1412"),
    ]

    operations = []
