# Generated by Django 6.0.3 on 2026-03-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_merge_20260324_2027"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="hire_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
