# Generated by Django 6.0.3 on 2026-03-30 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_add_hire_date_to_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeavePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("vacation", "Vacation"),
                            ("sick", "Sick Leave"),
                            ("wfh", "Work From Home"),
                            ("personal", "Personal"),
                            ("maternity", "Maternity"),
                            ("paternity", "Paternity"),
                            ("bereavement", "Bereavement"),
                            ("unpaid", "Unpaid Leave"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "allocated_days_per_year",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of days allocated per year"
                    ),
                ),
                (
                    "carryover_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Maximum days that can be carried over to next year",
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this leave type requires manager approval",
                    ),
                ),
                (
                    "requires_covering_employee",
                    models.BooleanField(
                        default=False,
                        help_text="Whether a covering employee must be assigned",
                    ),
                ),
                (
                    "min_notice_in_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum days notice required before leave start date",
                    ),
                ),
                (
                    "max_consecutive_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum consecutive days allowed (optional)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Leave Policy",
                "verbose_name_plural": "Leave Policies",
                "ordering": ["leave_type"],
            },
        ),
        migrations.CreateModel(
            name="LeaveAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("vacation", "Vacation"),
                            ("sick", "Sick Leave"),
                            ("wfh", "Work From Home"),
                            ("personal", "Personal"),
                            ("maternity", "Maternity"),
                            ("paternity", "Paternity"),
                            ("bereavement", "Bereavement"),
                            ("unpaid", "Unpaid Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "old_allocated",
                    models.PositiveIntegerField(help_text="Previous allocated days"),
                ),
                (
                    "new_allocated",
                    models.PositiveIntegerField(help_text="New allocated days"),
                ),
                ("reason", models.TextField(help_text="Reason for adjustment")),
                ("adjusted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "adjusted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adjustments_made",
                        to="core.userprofile",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_adjustments",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Adjustment",
                "verbose_name_plural": "Leave Adjustments",
                "ordering": ["-adjusted_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("vacation", "Vacation"),
                            ("sick", "Sick Leave"),
                            ("wfh", "Work From Home"),
                            ("personal", "Personal"),
                            ("maternity", "Maternity"),
                            ("paternity", "Paternity"),
                            ("bereavement", "Bereavement"),
                            ("unpaid", "Unpaid Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submitted_date", models.DateTimeField(auto_now_add=True)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                (
                    "approval_comments",
                    models.TextField(blank=True, help_text="Comments from approver"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, help_text="Reason for rejection"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manager who approved/rejected",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to="core.userprofile",
                    ),
                ),
                (
                    "covering_employee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employee covering during leave",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="covering_for",
                        to="core.userprofile",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Request",
                "verbose_name_plural": "Leave Requests",
                "ordering": ["-submitted_date"],
            },
        ),
        migrations.CreateModel(
            name="LeaveApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_chain",
                    models.JSONField(
                        default=list,
                        help_text="List of approver user profile IDs in order",
                    ),
                ),
                ("current_step", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "comments",
                    models.JSONField(
                        default=list,
                        help_text="List of comments from each approval step",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_approvals",
                        to="core.userprofile",
                    ),
                ),
                (
                    "leave_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_workflow",
                        to="core.leaverequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Approval Workflow",
                "verbose_name_plural": "Leave Approval Workflows",
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("vacation", "Vacation"),
                            ("sick", "Sick Leave"),
                            ("wfh", "Work From Home"),
                            ("personal", "Personal"),
                            ("maternity", "Maternity"),
                            ("paternity", "Paternity"),
                            ("bereavement", "Bereavement"),
                            ("unpaid", "Unpaid Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "allocated",
                    models.PositiveIntegerField(
                        default=0, help_text="Total days allocated for this period"
                    ),
                ),
                (
                    "used",
                    models.PositiveIntegerField(
                        default=0, help_text="Days already used/approved"
                    ),
                ),
                (
                    "carryover",
                    models.PositiveIntegerField(
                        default=0, help_text="Days carried over from previous year"
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="Calendar year for this balance"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Balance",
                "verbose_name_plural": "Leave Balances",
                "ordering": ["-year", "employee", "leave_type"],
                "unique_together": {("employee", "leave_type", "year")},
            },
        ),
    ]
