# Generated by Django 6.0.3 on 2026-03-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_add_hire_date_to_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="app_stack",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="client",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="start_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
