# Generated by Django 6.0.3 on 2026-04-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_cpflevel"),
        ("core", "0014_project_app_stack_project_client_and_more"),
    ]

    operations = []
