# Generated by Django 6.0.3 on 2026-04-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_merge_20260401_1814"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["name"],
            },
        ),
    ]
