# Generated by Django 6.0.3 on 2026-04-01 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_add_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="cpflevel",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cpf_levels",
                to="core.role",
            ),
        ),
    ]
