# Generated by Django 6.0.3 on 2026-04-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_link_cpflevel_to_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="manager",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="managers",
            field=models.ManyToManyField(
                blank=True, related_name="direct_reports", to="core.userprofile"
            ),
        ),
    ]
