# Generated by Django 6.0.3 on 2026-04-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_userprofile_manager_userprofile_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("on_hold", "On Hold"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="assigned_projects",
            field=models.ManyToManyField(
                blank=True,
                related_name="employees",
                through="core.ProjectAssignment",
                to="core.project",
            ),
        ),
    ]
