# Generated by Django 6.0.3 on 2026-04-22 22:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_employee_document_mixed_source_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedocument",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=core.models.employee_document_upload_to
            ),
        ),
    ]
