# Generated by Django 6.0.3 on 2026-04-23 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_employee_document_upload_path_by_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeProfileChangeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("role", "Role"),
                            ("salary", "Salary"),
                            ("cpf_level", "CPF Level"),
                        ],
                        max_length=32,
                    ),
                ),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_profile_changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_change_history",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Profile Change History",
                "verbose_name_plural": "Employee Profile Change History",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "-changed_at"],
                        name="core_employ_employe_933515_idx",
                    ),
                    models.Index(fields=["field"], name="core_employ_field_ad2ac7_idx"),
                ],
            },
        ),
    ]
