# Generated by Django 6.0.3 on 2026-04-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_employeeprofilechangehistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofilechangehistory",
            name="field",
            field=models.CharField(
                choices=[
                    ("role", "Role"),
                    ("salary", "Salary"),
                    ("cpf_level", "CPF Level"),
                    ("department", "Department"),
                    ("manager_ids", "Manager IDs"),
                    ("employment_status", "Employment Status"),
                    ("career_level", "Career Level"),
                    ("start_date", "Start Date"),
                ],
                max_length=32,
            ),
        ),
    ]
