# Generated by Django 6.0.3 on 2026-04-22 19:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_employeeprofilechangehistory_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("quarterly", "Quarterly Review"),
                            ("mid_year", "Mid-Year Review"),
                            ("annual", "Annual Review"),
                            ("probation", "Probation Review"),
                            ("custom", "Custom Review"),
                        ],
                        default="quarterly",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "scheduled_date",
                    models.DateField(
                        help_text="Date on which the formal performance review is due."
                    ),
                ),
                (
                    "next_review_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional follow-up review date for the next cycle.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("exceeds_expectations", "Exceeds Expectations"),
                            ("meets_expectations", "Meets Expectations"),
                            ("partially_meets", "Partially Meets Expectations"),
                            ("needs_improvement", "Needs Improvement"),
                            ("unsatisfactory", "Unsatisfactory"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "overall_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Overall review rating on a 1-5 scale.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "performance_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Optional normalized performance score (0-100).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "cpf_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Optional CPF score (0-100).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "cpf_current_level",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "cpf_recommended_level",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="High-level review outcome summary.",
                    ),
                ),
                ("employee_comments", models.TextField(blank=True, default="")),
                ("reviewer_comments", models.TextField(blank=True, default="")),
                (
                    "reminder_offsets_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Reminder offsets (days before scheduled date) used by reminder jobs.",
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_reviews_created",
                        to="core.userprofile",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reviews",
                        to="core.userprofile",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews_to_conduct",
                        to="core.userprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_reviews_updated",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Review",
                "verbose_name_plural": "Performance Reviews",
                "ordering": ["-scheduled_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceReviewActionPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_review_action_points_created",
                        to="core.userprofile",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_review_action_points",
                        to="core.userprofile",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_points",
                        to="core.performancereview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Review Action Point",
                "verbose_name_plural": "Performance Review Action Points",
                "ordering": ["due_date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceReviewAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="performance_reviews/attachments/%Y/%m/%d/"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.performancereview",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_review_attachments",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Review Attachment",
                "verbose_name_plural": "Performance Review Attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceReviewHistoryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("scheduled", "Scheduled"),
                            ("rescheduled", "Rescheduled"),
                            ("status_changed", "Status Changed"),
                            ("outcome_updated", "Outcome Updated"),
                            ("note_added", "Note Added"),
                            ("note_updated", "Note Updated"),
                            ("action_point_added", "Action Point Added"),
                            ("action_point_updated", "Action Point Updated"),
                            ("attachment_added", "Attachment Added"),
                            ("attachment_removed", "Attachment Removed"),
                            ("reminder_generated", "Reminder Generated"),
                            ("reminder_read", "Reminder Read"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_review_history_events",
                        to="core.userprofile",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_events",
                        to="core.performancereview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Review History Event",
                "verbose_name_plural": "Performance Review History Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceReviewNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("shared", "Shared"), ("private", "Private")],
                        default="shared",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_review_notes",
                        to="core.userprofile",
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_review_notes_edited",
                        to="core.userprofile",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="core.performancereview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Review Note",
                "verbose_name_plural": "Performance Review Notes",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceReviewReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("due_today", "Due Today"),
                            ("overdue", "Overdue"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(blank=True, default="", max_length=255)),
                ("scheduled_for", models.DateTimeField()),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_review_reminders",
                        to="core.userprofile",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="core.performancereview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Review Reminder",
                "verbose_name_plural": "Performance Review Reminders",
                "ordering": ["-scheduled_for", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="performancereview",
            index=models.Index(
                fields=["status", "scheduled_date"],
                name="core_perfor_status_1304b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="performancereview",
            index=models.Index(
                fields=["employee", "scheduled_date"],
                name="core_perfor_employe_f06822_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="performancereview",
            index=models.Index(
                fields=["reviewer", "scheduled_date"],
                name="core_perfor_reviewe_1d18bc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="performancereview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("overall_rating__isnull", True),
                    models.Q(("overall_rating__gte", 1), ("overall_rating__lte", 5)),
                    _connector="OR",
                ),
                name="perf_review_rating_between_1_and_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="performancereview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("performance_score__isnull", True),
                    models.Q(
                        ("performance_score__gte", 0), ("performance_score__lte", 100)
                    ),
                    _connector="OR",
                ),
                name="perf_review_performance_score_between_0_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="performancereview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cpf_score__isnull", True),
                    models.Q(("cpf_score__gte", 0), ("cpf_score__lte", 100)),
                    _connector="OR",
                ),
                name="perf_review_cpf_score_between_0_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="performancereview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("period_start__isnull", True),
                    ("period_end__isnull", True),
                    ("period_start__lte", models.F("period_end")),
                    _connector="OR",
                ),
                name="perf_review_period_start_before_end",
            ),
        ),
        migrations.AddIndex(
            model_name="performancereviewactionpoint",
            index=models.Index(
                fields=["review", "status"], name="core_perfor_review__5cdc5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancereviewactionpoint",
            index=models.Index(
                fields=["owner", "due_date"], name="core_perfor_owner_i_225a7b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="performancereviewactionpoint",
            constraint=models.CheckConstraint(
                condition=models.Q(("progress__gte", 0), ("progress__lte", 100)),
                name="perf_review_action_point_progress_between_0_100",
            ),
        ),
        migrations.AddIndex(
            model_name="performancereviewattachment",
            index=models.Index(
                fields=["review", "created_at"], name="core_perfor_review__c9968d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancereviewattachment",
            index=models.Index(
                fields=["uploaded_by", "created_at"],
                name="core_perfor_uploade_fcdabb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="performancereviewhistoryevent",
            index=models.Index(
                fields=["review", "created_at"], name="core_perfor_review__a24ce6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancereviewhistoryevent",
            index=models.Index(
                fields=["event_type", "created_at"],
                name="core_perfor_event_t_65cee8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="performancereviewnote",
            index=models.Index(
                fields=["review", "visibility"], name="core_perfor_review__6b79fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancereviewnote",
            index=models.Index(
                fields=["author", "created_at"], name="core_perfor_author__8e0f0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancereviewreminder",
            index=models.Index(
                fields=["recipient", "is_read", "scheduled_for"],
                name="core_perfor_recipie_6db84f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="performancereviewreminder",
            index=models.Index(
                fields=["is_sent", "scheduled_for"],
                name="core_perfor_is_sent_d6298c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="performancereviewreminder",
            index=models.Index(
                fields=["review", "reminder_type"],
                name="core_perfor_review__01a7f6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="performancereviewreminder",
            constraint=models.UniqueConstraint(
                fields=("review", "recipient", "reminder_type", "scheduled_for"),
                name="perf_review_reminder_unique_slot",
            ),
        ),
    ]
