# Generated by Django 6.0.3 on 2026-05-01 — rewritten to be idempotent
# Uses SeparateDatabaseAndState so Django's model-state stays correct while
# the SQL is fully safe to re-run against a partially-migrated database.
#
# Why idempotent?  A previous version of this migration was partially applied
# (some Document columns already exist in the DB).  Every operation below uses
# IF NOT EXISTS / conditional DO blocks so it is safe to run in any state.

import django.db.models.deletion
from django.db import migrations, models


class SeparateDatabaseAndStatePostgresOnly(migrations.SeparateDatabaseAndState):
    """
    On PostgreSQL: applies database_operations (idempotent SQL) to the actual DB.
    On other backends (SQLite for tests): applies state_operations to both the
    model state and the actual DB, just like regular migration operations.
    """

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == "postgresql":
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        else:
            state = from_state.clone()
            for operation in self.state_operations:
                new_state = state.clone()
                operation.state_forwards(app_label, new_state)
                operation.database_forwards(app_label, schema_editor, state, new_state)
                state = new_state

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == "postgresql":
            super().database_backwards(app_label, schema_editor, from_state, to_state)


# ──────────────────────────────────────────────────────────────────────────────
# New tables
# ──────────────────────────────────────────────────────────────────────────────

_CREATE_DOCUMENTSIGNER = """
CREATE TABLE IF NOT EXISTS "core_documentsigner" (
    "id"         bigserial                NOT NULL PRIMARY KEY,
    "name"       varchar(255)             NOT NULL,
    "email"      varchar(254)             NOT NULL,
    "status"     varchar(20)              NOT NULL DEFAULT 'notsent',
    "signed_at"  timestamp with time zone NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT NOW()
);
"""
_DROP_DOCUMENTSIGNER = 'DROP TABLE IF EXISTS "core_documentsigner";'

_CREATE_DOCUMENTVERSION = """
CREATE TABLE IF NOT EXISTS "core_documentversion" (
    "id"          bigserial                NOT NULL PRIMARY KEY,
    "version"     varchar(20)              NOT NULL,
    "file_key"    varchar(500)             NOT NULL,
    "file_size"   bigint                   NOT NULL DEFAULT 0,
    "uploaded_at" timestamp with time zone NOT NULL DEFAULT NOW(),
    "notes"       text                     NOT NULL DEFAULT ''
);
"""
_DROP_DOCUMENTVERSION = 'DROP TABLE IF EXISTS "core_documentversion";'


# ──────────────────────────────────────────────────────────────────────────────
# FK columns on DocumentSigner / DocumentVersion (idempotent ADD COLUMN)
# ──────────────────────────────────────────────────────────────────────────────

_ADD_SIGNER_DOCUMENT_FK = """
ALTER TABLE "core_documentsigner"
    ADD COLUMN IF NOT EXISTS "document_id" bigint NOT NULL
        REFERENCES "core_document" ("id") DEFERRABLE INITIALLY DEFERRED;
"""

_ADD_VERSION_DOCUMENT_FK = """
ALTER TABLE "core_documentversion"
    ADD COLUMN IF NOT EXISTS "document_id" bigint NOT NULL
        REFERENCES "core_document" ("id") DEFERRABLE INITIALLY DEFERRED;
"""

_ADD_VERSION_UPLOADER_FK = """
ALTER TABLE "core_documentversion"
    ADD COLUMN IF NOT EXISTS "uploaded_by_id" bigint NULL
        REFERENCES "core_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED;
"""

# Unique constraint on (document_id, version) for DocumentVersion
_ADD_DOCVERSION_UNIQUE = """
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'core_documentversion'::regclass
          AND contype  = 'u'
          AND conname  = 'core_documentversion_document_id_version_key'
    ) THEN
        ALTER TABLE "core_documentversion"
            ADD CONSTRAINT "core_documentversion_document_id_version_key"
            UNIQUE ("document_id", "version");
    END IF;
END $$;
"""


# ──────────────────────────────────────────────────────────────────────────────
# Document: drop old index
# ──────────────────────────────────────────────────────────────────────────────

_DROP_OLD_EMPLOYEE_IDX = 'DROP INDEX IF EXISTS "core_docume_employe_9c18ac_idx";'


# ──────────────────────────────────────────────────────────────────────────────
# Document: add new columns (all IF NOT EXISTS — safe to re-run)
# ──────────────────────────────────────────────────────────────────────────────

_ADD_DOCUMENT_COLUMNS = """
ALTER TABLE "core_document"
    ADD COLUMN IF NOT EXISTS "allowed_roles"     jsonb        NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS "archived"          boolean      NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS "current_version"   varchar(20)  NOT NULL DEFAULT '1.0',
    ADD COLUMN IF NOT EXISTS "description"       text         NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS "file_size"         bigint       NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "is_confidential"   boolean      NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS "mime_type"         varchar(100) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS "original_filename" varchar(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS "signature_status"  varchar(20)  NOT NULL DEFAULT 'not_required',
    ADD COLUMN IF NOT EXISTS "tags"              jsonb        NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS "updated_at"        timestamp with time zone NULL;
"""

# uploaded_by_id FK — add column first, then FK constraint separately so that
# IF NOT EXISTS on the column doesn't skip the constraint if it's missing.
_ADD_UPLOADED_BY_COL = """
ALTER TABLE "core_document"
    ADD COLUMN IF NOT EXISTS "uploaded_by_id" bigint NULL;
"""

_ADD_UPLOADED_BY_FK = """
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu
            ON tc.constraint_name = kcu.constraint_name
           AND tc.table_schema    = kcu.table_schema
        WHERE tc.constraint_type = 'FOREIGN KEY'
          AND tc.table_schema    = current_schema()
          AND tc.table_name      = 'core_document'
          AND kcu.column_name    = 'uploaded_by_id'
    ) THEN
        ALTER TABLE "core_document"
            ADD CONSTRAINT "core_document_uploaded_by_id_fkey"
            FOREIGN KEY ("uploaded_by_id")
            REFERENCES "core_userprofile" ("id")
            DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;
"""


# ──────────────────────────────────────────────────────────────────────────────
# Document: make employee_id nullable
# DROP NOT NULL is a no-op if the column is already nullable — safe to re-run.
# ──────────────────────────────────────────────────────────────────────────────

_EMPLOYEE_NULLABLE = """
ALTER TABLE "core_document" ALTER COLUMN "employee_id" DROP NOT NULL;
"""


# ──────────────────────────────────────────────────────────────────────────────
# Document: migrate category from FK → CharField
#
# Old schema: column "category_id" (integer FK → core_documentcategory)
# New schema: column "category"    (varchar(20) with TextChoices)
#
# The DECLARE must be at the top of the DO block in PostgreSQL.
# ──────────────────────────────────────────────────────────────────────────────

_MIGRATE_CATEGORY = """
DO $$
DECLARE
    _fk_name text;
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name   = 'core_document'
          AND column_name  = 'category_id'
    ) THEN
        -- Find the FK constraint name (if any) and drop it
        SELECT tc.constraint_name INTO _fk_name
        FROM information_schema.table_constraints  tc
        JOIN information_schema.key_column_usage   kcu
            ON  tc.constraint_name = kcu.constraint_name
            AND tc.table_schema    = kcu.table_schema
        WHERE tc.constraint_type = 'FOREIGN KEY'
          AND tc.table_schema    = current_schema()
          AND tc.table_name      = 'core_document'
          AND kcu.column_name    = 'category_id'
        LIMIT 1;

        IF _fk_name IS NOT NULL THEN
            EXECUTE format('ALTER TABLE core_document DROP CONSTRAINT %I', _fk_name);
        END IF;

        ALTER TABLE "core_document" DROP COLUMN "category_id";
        ALTER TABLE "core_document" ADD COLUMN "category" varchar(20) NOT NULL DEFAULT 'other';
    END IF;
    -- If category_id does not exist, "category" CharField is already in place — nothing to do.
END $$;
"""


# ──────────────────────────────────────────────────────────────────────────────
# Document: new indexes
# CREATE INDEX IF NOT EXISTS is available since PostgreSQL 9.5.
# ──────────────────────────────────────────────────────────────────────────────

_ADD_CATEGORY_IDX = 'CREATE INDEX IF NOT EXISTS "core_docume_categor_3e28f6_idx"  ON "core_document" ("category");'
_ADD_SIG_STATUS_IDX = 'CREATE INDEX IF NOT EXISTS "core_docume_signatu_ff6c5d_idx"  ON "core_document" ("signature_status");'
_ADD_ARCHIVED_IDX = 'CREATE INDEX IF NOT EXISTS "core_docume_archive_5bb3c6_idx"  ON "core_document" ("archived");'
_ADD_EXPIRY_IDX = 'CREATE INDEX IF NOT EXISTS "core_docume_expiry__8c27b8_idx"  ON "core_document" ("expiry_date");'


# ──────────────────────────────────────────────────────────────────────────────
# Migration class
# ──────────────────────────────────────────────────────────────────────────────


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_documentcategory_document"),
    ]

    operations = [
        SeparateDatabaseAndStatePostgresOnly(
            # ── Real SQL (idempotent) ─────────────────────────────────────
            database_operations=[
                # New tables
                migrations.RunSQL(
                    _CREATE_DOCUMENTSIGNER, reverse_sql=_DROP_DOCUMENTSIGNER
                ),
                migrations.RunSQL(
                    _CREATE_DOCUMENTVERSION, reverse_sql=_DROP_DOCUMENTVERSION
                ),
                # FK columns on new tables
                migrations.RunSQL(
                    _ADD_SIGNER_DOCUMENT_FK, reverse_sql=migrations.RunSQL.noop
                ),
                migrations.RunSQL(
                    _ADD_VERSION_DOCUMENT_FK, reverse_sql=migrations.RunSQL.noop
                ),
                migrations.RunSQL(
                    _ADD_VERSION_UPLOADER_FK, reverse_sql=migrations.RunSQL.noop
                ),
                migrations.RunSQL(
                    _ADD_DOCVERSION_UNIQUE, reverse_sql=migrations.RunSQL.noop
                ),
                # Document changes
                migrations.RunSQL(
                    _DROP_OLD_EMPLOYEE_IDX, reverse_sql=migrations.RunSQL.noop
                ),
                migrations.RunSQL(
                    _ADD_DOCUMENT_COLUMNS, reverse_sql=migrations.RunSQL.noop
                ),
                migrations.RunSQL(
                    _ADD_UPLOADED_BY_COL, reverse_sql=migrations.RunSQL.noop
                ),
                migrations.RunSQL(
                    _ADD_UPLOADED_BY_FK, reverse_sql=migrations.RunSQL.noop
                ),
                migrations.RunSQL(
                    _EMPLOYEE_NULLABLE, reverse_sql=migrations.RunSQL.noop
                ),
                migrations.RunSQL(
                    _MIGRATE_CATEGORY, reverse_sql=migrations.RunSQL.noop
                ),
                # New indexes
                migrations.RunSQL(
                    _ADD_CATEGORY_IDX, reverse_sql=migrations.RunSQL.noop
                ),
                migrations.RunSQL(
                    _ADD_SIG_STATUS_IDX, reverse_sql=migrations.RunSQL.noop
                ),
                migrations.RunSQL(
                    _ADD_ARCHIVED_IDX, reverse_sql=migrations.RunSQL.noop
                ),
                migrations.RunSQL(_ADD_EXPIRY_IDX, reverse_sql=migrations.RunSQL.noop),
            ],
            # ── Django model-state operations (no SQL executed) ───────────
            state_operations=[
                migrations.CreateModel(
                    name="DocumentSigner",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("name", models.CharField(max_length=255)),
                        ("email", models.EmailField(max_length=254)),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("pending", "Pending"),
                                    ("signed", "Signed"),
                                    ("notsent", "Not Sent"),
                                ],
                                default="notsent",
                                max_length=20,
                            ),
                        ),
                        ("signed_at", models.DateTimeField(blank=True, null=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        "verbose_name": "Document Signer",
                        "verbose_name_plural": "Document Signers",
                        "ordering": ["created_at"],
                    },
                ),
                migrations.CreateModel(
                    name="DocumentVersion",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("version", models.CharField(max_length=20)),
                        ("file_key", models.CharField(max_length=500)),
                        ("file_size", models.PositiveBigIntegerField(default=0)),
                        ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                        ("notes", models.TextField(blank=True, default="")),
                    ],
                    options={
                        "verbose_name": "Document Version",
                        "verbose_name_plural": "Document Versions",
                        "ordering": ["version"],
                    },
                ),
                migrations.AlterModelOptions(
                    name="document",
                    options={
                        "ordering": ["-updated_at"],
                        "verbose_name": "Document",
                        "verbose_name_plural": "Documents",
                    },
                ),
                migrations.RemoveIndex(
                    model_name="document", name="core_docume_employe_9c18ac_idx"
                ),
                migrations.AddField(
                    model_name="document",
                    name="allowed_roles",
                    field=models.JSONField(blank=True, default=list),
                ),
                migrations.AddField(
                    model_name="document",
                    name="archived",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="document",
                    name="current_version",
                    field=models.CharField(default="1.0", max_length=20),
                ),
                migrations.AddField(
                    model_name="document",
                    name="description",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="document",
                    name="file_size",
                    field=models.PositiveBigIntegerField(default=0),
                ),
                migrations.AddField(
                    model_name="document",
                    name="is_confidential",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="document",
                    name="mime_type",
                    field=models.CharField(blank=True, default="", max_length=100),
                ),
                migrations.AddField(
                    model_name="document",
                    name="original_filename",
                    field=models.CharField(blank=True, default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="document",
                    name="signature_status",
                    field=models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("signed", "Signed"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("not_required", "Not Required"),
                        ],
                        default="not_required",
                        max_length=20,
                    ),
                ),
                migrations.AddField(
                    model_name="document",
                    name="tags",
                    field=models.JSONField(blank=True, default=list),
                ),
                migrations.AddField(
                    model_name="document",
                    name="updated_at",
                    field=models.DateTimeField(auto_now=True),
                ),
                migrations.AddField(
                    model_name="document",
                    name="uploaded_by",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to="core.userprofile",
                    ),
                ),
                migrations.AlterField(
                    model_name="document",
                    name="category",
                    field=models.CharField(
                        choices=[
                            ("contracts", "Contracts"),
                            ("policies", "Policies"),
                            ("agreements", "Agreements"),
                            ("compliance", "Compliance"),
                            ("onboarding", "Onboarding"),
                            ("training", "Training"),
                            ("benefits", "Benefits"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                migrations.AlterField(
                    model_name="document",
                    name="employee",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_documents",
                        to="core.userprofile",
                    ),
                ),
                migrations.AddIndex(
                    model_name="document",
                    index=models.Index(
                        fields=["category"], name="core_docume_categor_3e28f6_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="document",
                    index=models.Index(
                        fields=["signature_status"],
                        name="core_docume_signatu_ff6c5d_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="document",
                    index=models.Index(
                        fields=["archived"], name="core_docume_archive_5bb3c6_idx"
                    ),
                ),
                migrations.AddField(
                    model_name="documentsigner",
                    name="document",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signers",
                        to="core.document",
                    ),
                ),
                migrations.AddField(
                    model_name="documentversion",
                    name="document",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="core.document",
                    ),
                ),
                migrations.AddField(
                    model_name="documentversion",
                    name="uploaded_by",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_versions",
                        to="core.userprofile",
                    ),
                ),
                migrations.AlterUniqueTogether(
                    name="documentversion",
                    unique_together={("document", "version")},
                ),
            ],
        ),
    ]
