# Generated by Django 6.0.3 on 2026-05-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_certificate_peersession_trainingbudget_trainingentry"),
        ("core", "0028_document_full_schema"),
    ]

    operations = []
