# Generated by Django 6.0.3 on 2026-05-02 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_merge_20260501_2036"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HR", "HR"),
                            ("LEGAL", "Legal"),
                            ("FINANCE", "Finance"),
                            ("OPERATIONS", "Operations"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("content", models.JSONField(default=dict)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PRIVATE", "Private"), ("SHARED", "Shared")],
                        default="PRIVATE",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("is_system_template", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Template",
                "verbose_name_plural": "Document Templates",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("field_key", models.CharField(max_length=100)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("DATE", "Date"),
                            ("NUMBER", "Number"),
                            ("DROPDOWN", "Dropdown"),
                            ("CHECKBOX", "Checkbox"),
                            ("USER_SELECT", "User Select"),
                        ],
                        default="TEXT",
                        max_length=15,
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "default_value",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("options", models.JSONField(blank=True, default=None, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="core.documenttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Field",
                "verbose_name_plural": "Template Fields",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TemplateGeneratedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("resolved_content", models.JSONField(default=dict)),
                ("field_values", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_documents",
                        to="core.userprofile",
                    ),
                ),
                (
                    "source_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_documents",
                        to="core.documenttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Document",
                "verbose_name_plural": "Generated Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="documenttemplate",
            index=models.Index(
                fields=["category"], name="core_docume_categor_26d471_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documenttemplate",
            index=models.Index(
                fields=["visibility"], name="core_docume_visibil_942059_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documenttemplate",
            index=models.Index(
                fields=["is_active"], name="core_docume_is_acti_443df5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documenttemplate",
            index=models.Index(
                fields=["is_system_template"], name="core_docume_is_syst_7ce23a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documenttemplate",
            index=models.Index(
                fields=["created_by"], name="core_docume_created_a93dee_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="templatefield",
            unique_together={("template", "field_key")},
        ),
    ]
