# Generated by Django 6.0.3 on 2026-05-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_document_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("contract", "Contract"),
                    ("policy", "Policy"),
                    ("agreement", "Agreement"),
                    ("onboarding", "Onboarding"),
                    ("compliance", "Compliance"),
                    ("training", "Training"),
                    ("benefits", "Benefits"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("inactive", "Inactive"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="visibility",
            field=models.CharField(
                choices=[("private", "Private"), ("shared", "Shared")],
                default="private",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="default_value",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("date", "Date"),
                    ("number", "Number"),
                    ("dropdown", "Dropdown"),
                    ("checkbox", "Checkbox"),
                    ("user_select", "User Select"),
                ],
                default="text",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="is_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="options",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="placeholder",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="templategenerateddocument",
            name="resolved_content",
            field=models.TextField(blank=True, default=""),
        ),
    ]
