# Generated by Django 6.0.3 on 2026-05-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_documenttemplate_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingentry",
            name="certificate_link",
            field=models.URLField(
                blank=True,
                help_text="HTTPS URL link to the training certificate",
                null=True,
            ),
        ),
    ]
