# Generated by Django 6.0.3 on 2026-05-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_add_certificate_link_to_trainingentry"),
        ("core", "0032_seed_default_leave_data"),
    ]

    operations = []
