# Generated by Django 6.0.3 on 2026-05-05 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_merge_20260505_1543"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTemplateSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("html", models.TextField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_snippets",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Template Snippet",
                "verbose_name_plural": "User Template Snippets",
                "ordering": ["sort_order", "-updated_at"],
            },
        ),
    ]
