# Generated by Django 6.0.3 on 2026-05-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_user_template_snippet"),
        ("core", "0036_alter_leave_request_hr_approval_help_text"),
    ]

    operations = []
