# Generated by Codex on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_merge_20260507_1304"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replacementlog",
            name="date",
            field=models.DateField(help_text="Date when the replacement occurred"),
        ),
    ]
