# Generated by Django 6.0.3 on 2026-05-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_merge_20260507_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktemplate',
            name='role_responsible',
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='role_responsible',
            field=models.CharField(choices=[('HR', 'HR'), ('IT', 'IT'), ('Manager', 'Manager')], default='HR', max_length=20),
        ),
    ]
