# Generated by Django 6.0.3 on 2026-05-07 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_move_role_responsible_to_checklist_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistinstance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checklist_instances', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
