# Generated by Django 6.0.3 on 2026-05-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_document_visibility"),
        ("core", "0039_add_due_date_and_created_by_to_checklist_instance"),
    ]

    operations = []
