# Generated by Django 6.0.3 on 2026-05-11 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_merge_20260510_1223"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConferenceCourseRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the conference or course", max_length=255
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Scheduled date of the conference or course"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("attended", "Attended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="registered",
                        help_text="Attendance status",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Additional notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee registered for the conference or course",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_course_registrations",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conference / Course Registration",
                "verbose_name_plural": "Conference / Course Registrations",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["employee", "-date"],
                        name="core_confer_employe_e3919a_idx",
                    ),
                    models.Index(
                        fields=["status"], name="core_confer_status_158e1d_idx"
                    ),
                ],
            },
        ),
    ]
