# Generated by Django 6.0.3 on 2026-05-11 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_merge_20260510_1223"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSignatureAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("viewed", "Viewed"),
                            ("signed", "Signed"),
                            ("rejected", "Rejected"),
                            ("reminded", "Reminded"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Document Signature Audit Log",
                "verbose_name_plural": "Document Signature Audit Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="documentsigner",
            name="decline_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="documentsigner",
            name="declined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentsigner",
            name="last_reminded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentsigner",
            name="requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentsigner",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_document_signatures",
                to="core.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="documentsigner",
            name="signature_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="documentsigner",
            name="signature_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="documentsigner",
            name="signed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="document_signatures",
                to="core.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="documentsigner",
            name="signing_token_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="documentsigner",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("signed", "Signed"),
                    ("rejected", "Rejected"),
                    ("notsent", "Not Sent"),
                ],
                default="notsent",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="documentsigner",
            index=models.Index(
                fields=["document", "status"], name="core_docume_documen_4c5133_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentsigner",
            index=models.Index(
                fields=["document", "email"], name="core_docume_documen_d5f45a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentsigner",
            index=models.Index(
                fields=["signed_at"], name="core_docume_signed__a613e4_idx"
            ),
        ),
        migrations.AddField(
            model_name="documentsignatureauditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="document_signature_audit_events",
                to="core.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="documentsignatureauditlog",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signature_audit_events",
                to="core.document",
            ),
        ),
        migrations.AddField(
            model_name="documentsignatureauditlog",
            name="signer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_events",
                to="core.documentsigner",
            ),
        ),
        migrations.AddIndex(
            model_name="documentsignatureauditlog",
            index=models.Index(
                fields=["document", "event"], name="core_docume_documen_dec446_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentsignatureauditlog",
            index=models.Index(
                fields=["signer", "event"], name="core_docume_signer__515240_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentsignatureauditlog",
            index=models.Index(
                fields=["created_at"], name="core_docume_created_1efa3a_idx"
            ),
        ),
    ]
