# Generated by Django 6.0.3 on 2026-05-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_scheduledmaintenance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("maintenance", "Maintenance"),
                    ("retired", "Retired"),
                    ("lost", "Lost"),
                    ("returned", "Returned"),
                    ("damaged", "Damaged"),
                ],
                default="active",
                help_text="Current status of the asset",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="replacementlog",
            name="asset_status_after",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("maintenance", "Maintenance"),
                    ("retired", "Retired"),
                    ("lost", "Lost"),
                    ("returned", "Returned"),
                    ("damaged", "Damaged"),
                ],
                help_text="Asset status after the replacement or maintenance event",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="replacementlog",
            name="asset_status_before",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("maintenance", "Maintenance"),
                    ("retired", "Retired"),
                    ("lost", "Lost"),
                    ("returned", "Returned"),
                    ("damaged", "Damaged"),
                ],
                help_text="Asset status before the replacement or maintenance event",
                max_length=20,
                null=True,
            ),
        ),
    ]
