# Generated by Django 6.0.3 on 2026-05-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="visibility_scope",
            field=models.CharField(
                choices=[
                    ("roles", "Roles"),
                    ("only_me", "Only Me"),
                    ("project_group", "Project Group"),
                ],
                default="roles",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["visibility_scope"], name="core_docume_visibil_347d6f_idx"
            ),
        ),
    ]
