# Generated by Django 6.0.3 on 2026-05-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_add_conference_course_registration"),
        ("core", "0043_document_visibility_scope_and_more"),
    ]

    operations = []
