# Generated by Codex on 2026-05-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_alter_asset_status_and_more"),
        ("core", "0044_merge_20260512_1227"),
    ]

    operations = []
