# Generated by Django 6.0.3 on 2026-05-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_merge_20260513_0000"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingbudget",
            name="threshold_notified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the 80% threshold alert was last sent",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="module",
            field=models.CharField(
                choices=[
                    ("documents", "Documents"),
                    ("vacations", "Vacations"),
                    ("reviews", "Reviews"),
                    ("onboarding", "Onboarding"),
                    ("announcements", "Announcements"),
                    ("training", "Training"),
                    ("general", "General"),
                ],
                default="general",
                max_length=32,
            ),
        ),
    ]
