# Generated by Django 6.0.3 on 2026-05-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_alter_project_options_project_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("active", "Active"),
                    ("on_hold", "On Hold"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("archived", "Archived"),
                ],
                default="planned",
                max_length=20,
            ),
        ),
    ]
