# Generated by Django 6.0.3 on 2026-05-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_alter_project_options_project_created_at_and_more"),
        ("core", "0046_asset_qr_codes"),
        ("core", "0047_seed_training_budget_permissions"),
    ]

    operations = []
