# Generated by Django 6.0.3 on 2026-05-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_add_archived_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="stage",
            field=models.CharField(
                choices=[
                    ("intake", "Proposal request"),
                    ("scoping", "Scoping"),
                    ("triage", "Triage"),
                    ("estimation", "Estimation"),
                    ("review_approval", "Review & approval"),
                    ("proposal_sent", "Proposal sent"),
                    ("kickoff", "Team assembly & kick-off"),
                    ("delivery", "Delivery"),
                ],
                default="intake",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="stage_note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
