# Generated by Django 6.0.3 on 2026-05-19 08:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_merge_20260519_1033"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the internal role", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of the role",
                    ),
                ),
                (
                    "open_at",
                    models.DateTimeField(
                        help_text="When the listing opens for applications"
                    ),
                ),
                (
                    "close_at",
                    models.DateTimeField(
                        help_text="When the listing closes for applications"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        help_text="Current status of the listing",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the listing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_job_listings",
                        to="core.userprofile",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department offering the position",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_listings",
                        to="core.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Listing",
                "verbose_name_plural": "Job Listings",
                "ordering": ["-open_at"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("shortlisted", "Shortlisted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                            ("accepted", "Accepted"),
                        ],
                        default="submitted",
                        help_text="Current status of the application",
                        max_length=20,
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the application was submitted",
                    ),
                ),
                (
                    "cover_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional note from the applicant",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        help_text="Employee submitting the application",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to="core.userprofile",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        help_text="The job listing being applied to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="core.joblisting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Application",
                "verbose_name_plural": "Job Applications",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="PromotionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Effective date of the promotion")),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional context about the promotion",
                    ),
                ),
                (
                    "previous_cpf_level",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Snapshot of CPF level prior to promotion",
                        max_length=100,
                    ),
                ),
                (
                    "new_cpf_level",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Snapshot of CPF level after promotion",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee being promoted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_history",
                        to="core.userprofile",
                    ),
                ),
                (
                    "new_role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Role held after the promotion",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_history_new",
                        to="core.role",
                    ),
                ),
                (
                    "previous_role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Role held before the promotion",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_history_previous",
                        to="core.role",
                    ),
                ),
                (
                    "related_listing",
                    models.ForeignKey(
                        blank=True,
                        help_text="Internal listing that led to the promotion, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotions",
                        to="core.joblisting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion History",
                "verbose_name_plural": "Promotion Histories",
                "ordering": ["-date"],
            },
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["status", "-open_at"], name="core_joblis_status_6e135d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["department", "status"], name="core_joblis_departm_37be03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["listing", "status"], name="core_applic_listing_02adc1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["applicant", "-applied_at"],
                name="core_applic_applica_9d77e4_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("listing", "applicant")},
        ),
        migrations.AddIndex(
            model_name="promotionhistory",
            index=models.Index(
                fields=["employee", "-date"], name="core_promot_employe_adc86a_idx"
            ),
        ),
    ]
