# Generated by Django 6.0.3 on 2026-05-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_project_stage_project_stage_note"),
        ("core", "0049_joblisting_application_promotionhistory_and_more"),
    ]

    operations = []
