# Generated by Django 6.0.3 on 2026-05-20 12:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_merge_20260519_1344"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "jira_issue_key",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "jira_project_key",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_tasks",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Task",
                "verbose_name_plural": "Time Tasks",
                "ordering": ["project__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField()),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("24")),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("jira", "Jira"),
                            ("tempo", "Tempo"),
                            ("document_import", "Document Import"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "source_external_id",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("source_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "duplicate_fingerprint",
                    models.CharField(db_index=True, max_length=64),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_time_entries",
                        to="core.userprofile",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="core.userprofile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_entries",
                        to="core.project",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_time_entries",
                        to="core.userprofile",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_time_entries",
                        to="core.userprofile",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="time_entries",
                        to="core.timetask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Entry",
                "verbose_name_plural": "Time Entries",
                "ordering": ["-work_date", "employee_id", "project_id"],
            },
        ),
        migrations.CreateModel(
            name="TimeEntryAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("deleted", "Deleted"),
                            ("imported", "Imported"),
                            ("corrected", "Corrected"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="time_entry_audit_events",
                        to="core.userprofile",
                    ),
                ),
                (
                    "time_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="core.timeentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Entry Audit Event",
                "verbose_name_plural": "Time Entry Audit Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["time_entry", "event_type"],
                        name="core_timeen_time_en_da01c9_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="core_timeen_actor_i_6b6ba8_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="timetask",
            index=models.Index(
                fields=["project", "is_active"], name="core_timeta_project_439ab4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timetask",
            index=models.Index(
                fields=["jira_issue_key"], name="core_timeta_jira_is_ada056_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timetask",
            index=models.Index(
                fields=["jira_project_key"], name="core_timeta_jira_pr_c4ca15_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="timetask",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_time_task_name_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="timetask",
            constraint=models.UniqueConstraint(
                condition=models.Q(("jira_issue_key", ""), _negated=True),
                fields=("jira_issue_key",),
                name="unique_time_task_jira_issue_key",
            ),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["employee", "work_date"], name="core_timeen_employe_c66a27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["project", "work_date"], name="core_timeen_project_54547a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["status", "work_date"], name="core_timeen_status_f53c9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["source_type", "source_external_id"],
                name="core_timeen_source__eedcae_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="timeentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_external_id", ""), _negated=True),
                fields=("source_type", "source_external_id"),
                name="unique_time_entry_external_source",
            ),
        ),
    ]
