# Generated by Django 6.0.3 on 2026-05-22 18:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_merge_20260519_1344"),
    ]

    operations = [
        migrations.CreateModel(
            name="CPFLevelChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_level",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="CPF level before this change",
                        max_length=100,
                    ),
                ),
                (
                    "new_level",
                    models.CharField(
                        help_text="CPF level after this change", max_length=100
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(help_text="Date the new level took effect"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("performance_review", "Performance Review"),
                            ("promotion", "Promotion"),
                        ],
                        default="manual",
                        help_text="What triggered the level change",
                        max_length=20,
                    ),
                ),
                (
                    "cpf_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Optional CPF score (0-100) recorded at the time of change",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee whose CPF level changed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cpf_level_changes",
                        to="core.userprofile",
                    ),
                ),
                (
                    "performance_review",
                    models.ForeignKey(
                        blank=True,
                        help_text="Review whose outcome drove this change, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cpf_level_changes",
                        to="core.performancereview",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        blank=True,
                        help_text="Promotion record linked to this change, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cpf_level_changes",
                        to="core.promotionhistory",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who recorded the change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_cpf_level_changes",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "CPF Level Change",
                "verbose_name_plural": "CPF Level Changes",
                "ordering": ["-effective_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "-effective_date"],
                        name="core_cpflev_employe_8a0c12_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("cpf_score__isnull", True),
                            models.Q(("cpf_score__gte", 0), ("cpf_score__lte", 100)),
                            _connector="OR",
                        ),
                        name="cpf_level_change_score_between_0_100",
                    )
                ],
            },
        ),
    ]
