# Generated by Django 6.0.3 on 2026-05-22 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_merge_20260519_1344"),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("is_anonymous", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surveys_created",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey",
                "verbose_name_plural": "Surveys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "respondent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null if the survey is anonymous.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_responses",
                        to="core.userprofile",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="core.survey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey Response",
                "verbose_name_plural": "Survey Responses",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("choice", "Choice"),
                            ("scale", "Scale"),
                        ],
                        default="text",
                        max_length=16,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of option strings for choice questions; ignored otherwise.",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="core.survey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["survey_id", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free text for text questions, selected option for choice, numeric string for scale.",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="core.question",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="core.response",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer",
                "verbose_name_plural": "Answers",
                "indexes": [
                    models.Index(
                        fields=["question"], name="core_answer_questio_30e282_idx"
                    ),
                    models.Index(
                        fields=["response"], name="core_answer_respons_c50073_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question", "response"),
                        name="uniq_answer_per_question_response",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(blank=True, default="", max_length=64)),
                ("text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("under_review", "Under Review"),
                            ("planned", "Planned"),
                            ("implemented", "Implemented"),
                            ("declined", "Declined"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null if submitted anonymously.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggestions",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suggestion",
                "verbose_name_plural": "Suggestions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="core_sugges_status_4e2d64_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(
                fields=["survey", "-submitted_at"],
                name="core_respon_survey__742f7d_idx",
            ),
        ),
    ]
