# Generated by Django 6.0.3 on 2026-05-20 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_timetask_timeentry_timeentryauditevent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JiraConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_url", models.URLField(blank=True, default="")),
                (
                    "auth_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("api_token_encrypted", models.TextField(blank=True, default="")),
                ("enabled", models.BooleanField(default=False)),
                (
                    "last_test_status",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("last_test_message", models.TextField(blank=True, default="")),
                ("last_test_at", models.DateTimeField(blank=True, null=True)),
                ("last_test_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Jira Connection",
                "verbose_name_plural": "Jira Connections",
            },
        ),
        migrations.AlterField(
            model_name="timeentryauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("deleted", "Deleted"),
                    ("imported", "Imported"),
                    ("corrected", "Corrected"),
                    ("source_changed", "Source Changed"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="JiraIssueMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jira_issue_key", models.CharField(max_length=50, unique=True)),
                (
                    "jira_issue_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jira_issue_mappings",
                        to="core.timetask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jira Issue Mapping",
                "verbose_name_plural": "Jira Issue Mappings",
                "ordering": ["jira_issue_key"],
            },
        ),
        migrations.CreateModel(
            name="JiraProjectMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jira_project_key", models.CharField(max_length=50, unique=True)),
                (
                    "jira_project_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jira_project_mappings",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jira Project Mapping",
                "verbose_name_plural": "Jira Project Mappings",
                "ordering": ["jira_project_key"],
            },
        ),
        migrations.CreateModel(
            name="JiraUserMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jira_account_id", models.CharField(max_length=150, unique=True)),
                (
                    "jira_display_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jira_user_mappings",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jira User Mapping",
                "verbose_name_plural": "Jira User Mappings",
                "ordering": ["jira_display_name", "jira_account_id"],
            },
        ),
    ]
