# Generated by Django 6.0.3 on 2026-05-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_add_cpf_level_change"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cpflevel",
            options={
                "ordering": ["role", "order", "name"],
                "verbose_name": "CPF Level",
                "verbose_name_plural": "CPF Levels",
            },
        ),
        migrations.AddField(
            model_name="cpflevel",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Rank within the role's CPF ladder (1 = entry level).",
            ),
        ),
    ]
