# Generated by Django 6.0.3 on 2026-05-20 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_jiraconnection_alter_timeentryauditevent_event_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempoConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_url", models.URLField(default="https://api.tempo.io/4")),
                ("api_token_encrypted", models.TextField(blank=True, default="")),
                ("enabled", models.BooleanField(default=False)),
                (
                    "last_test_status",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("last_test_message", models.TextField(blank=True, default="")),
                ("last_test_at", models.DateTimeField(blank=True, null=True)),
                ("last_test_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tempo Connection",
                "verbose_name_plural": "Tempo Connections",
            },
        ),
        migrations.CreateModel(
            name="TempoAccountMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tempo_account_id", models.CharField(max_length=150, unique=True)),
                (
                    "tempo_account_key",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "tempo_account_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tempo_account_mappings",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tempo Account Mapping",
                "verbose_name_plural": "Tempo Account Mappings",
                "ordering": ["tempo_account_key", "tempo_account_id"],
            },
        ),
        migrations.CreateModel(
            name="TempoProjectMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tempo_project_id", models.CharField(max_length=150, unique=True)),
                (
                    "tempo_project_key",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "tempo_project_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tempo_project_mappings",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tempo Project Mapping",
                "verbose_name_plural": "Tempo Project Mappings",
                "ordering": ["tempo_project_key", "tempo_project_id"],
            },
        ),
        migrations.CreateModel(
            name="TempoTeamMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tempo_team_id", models.CharField(max_length=150, unique=True)),
                (
                    "tempo_team_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tempo_team_mappings",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tempo Team Mapping",
                "verbose_name_plural": "Tempo Team Mappings",
                "ordering": ["tempo_team_name", "tempo_team_id"],
            },
        ),
        migrations.CreateModel(
            name="TempoUserMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tempo_user_id", models.CharField(max_length=150, unique=True)),
                (
                    "tempo_display_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tempo_user_mappings",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tempo User Mapping",
                "verbose_name_plural": "Tempo User Mappings",
                "ordering": ["tempo_display_name", "tempo_user_id"],
            },
        ),
    ]
