# Generated by Django 6.0.3 on 2026-05-20 18:48

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_tempoconnection_tempoaccountmapping_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("jira", "Jira"),
                            ("tempo", "Tempo"),
                            ("document_import", "Document Import"),
                        ],
                        default="document_import",
                        max_length=30,
                    ),
                ),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "source_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.models.time_import_upload_to,
                    ),
                ),
                ("requested_filters", models.JSONField(blank=True, default=dict)),
                ("column_mapping", models.JSONField(blank=True, default=dict)),
                ("detected_columns", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("needs_mapping", "Needs Mapping"),
                            ("previewed", "Previewed"),
                            ("partially_committed", "Partially Committed"),
                            ("committed", "Committed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=30,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("valid_rows", models.PositiveIntegerField(default=0)),
                ("error_rows", models.PositiveIntegerField(default=0)),
                ("skipped_rows", models.PositiveIntegerField(default=0)),
                ("committed_rows", models.PositiveIntegerField(default=0)),
                ("validation_messages", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="time_import_batches",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Import Batch",
                "verbose_name_plural": "Time Import Batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimeImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sheet_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("table_index", models.PositiveIntegerField(blank=True, null=True)),
                ("row_number", models.PositiveIntegerField()),
                ("row_index", models.PositiveIntegerField()),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("parsed_data", models.JSONField(blank=True, default=dict)),
                (
                    "original_row_fingerprint",
                    models.CharField(db_index=True, max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("valid", "Valid"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                            ("committed", "Committed"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("validation_messages", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="core.timeimportbatch",
                    ),
                ),
                (
                    "committed_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_rows",
                        to="core.timeentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Import Row",
                "verbose_name_plural": "Time Import Rows",
                "ordering": ["batch_id", "row_index"],
            },
        ),
        migrations.AddIndex(
            model_name="timeimportbatch",
            index=models.Index(
                fields=["source_type", "status"], name="core_timeim_source__0ff8a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeimportbatch",
            index=models.Index(
                fields=["uploaded_by", "created_at"],
                name="core_timeim_uploade_ccb435_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timeimportrow",
            index=models.Index(
                fields=["batch", "status"], name="core_timeim_batch_i_5d94db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeimportrow",
            index=models.Index(
                fields=["original_row_fingerprint"],
                name="core_timeim_origina_69f4d8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="timeimportrow",
            constraint=models.UniqueConstraint(
                fields=("batch", "row_index"),
                name="unique_time_import_row_index_per_batch",
            ),
        ),
    ]
