# Generated by Django 6.0.3 on 2026-05-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_org_chart_backfill"),
        ("core", "0053_seed_cpf_levels"),
    ]

    operations = []
