# Generated by Django 6.0.3 on 2026-05-25 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_merge_20260525_1546"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="decided_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the terminal decision (accepted/rejected/withdrawn) was recorded",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Reviewer who set the current terminal status",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decided_applications",
                to="core.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="decision_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Reviewer note captured when the application reaches a terminal state",
            ),
        ),
    ]
