# Generated by Django 6.0.3 on 2026-05-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_merge_20260525_1546"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("closed", "Closed"),
                ],
                default="draft",
                help_text="Lifecycle state. Closed surveys keep responses but reject new ones.",
                max_length=16,
            ),
        ),
    ]
