# Generated by Django 6.0.3 on 2026-05-25 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_merge_0052_org_chart_backfill_0053_seed_cpf_levels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField(unique=True)),
                ("total_monthly", models.DecimalField(decimal_places=2, max_digits=14)),
                ("avg_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("median_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("headcount", models.PositiveIntegerField()),
                ("currency", models.CharField(default="BAM", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Payroll Snapshot",
                "verbose_name_plural": "Payroll Snapshots",
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="BonusRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_type",
                    models.CharField(
                        choices=[
                            ("performance", "Performance"),
                            ("retention", "Retention"),
                            ("referral", "Referral"),
                            ("project", "Project"),
                            ("education", "Education"),
                            ("spot", "Spot"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="BAM", max_length=3)),
                ("effective_date", models.DateField()),
                ("reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bonuses_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonus_records",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bonus Record",
                "verbose_name_plural": "Bonus Records",
                "ordering": ["-effective_date"],
                "indexes": [
                    models.Index(
                        fields=["user_profile", "-effective_date"],
                        name="core_bonusr_user_pr_0c2c2c_idx",
                    ),
                    models.Index(
                        fields=["bonus_type"], name="core_bonusr_bonus_t_f26f78_idx"
                    ),
                ],
            },
        ),
    ]
