# Generated by Django 6.0.3 on 2026-05-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_timeimportbatch_timeimportrow_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeimportbatch",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("jira", "Jira"),
                    ("tempo", "Tempo"),
                    ("document_import", "Document Import"),
                ],
                default="document_import",
                max_length=30,
            ),
        ),
    ]
