# Generated by Django 6.0.3 on 2026-05-26 17:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_application_decision_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveBalanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("vacation", "Vacation"),
                            ("sick", "Sick Leave"),
                            ("wfh", "Work From Home"),
                            ("personal", "Personal"),
                            ("maternity", "Maternity"),
                            ("paternity", "Paternity"),
                            ("bereavement", "Bereavement"),
                            ("unpaid", "Unpaid Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="Calendar year for the balance"
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateField(
                        help_text="Date the snapshot was taken (UTC date)"
                    ),
                ),
                ("allocated", models.PositiveIntegerField(default=0)),
                ("used", models.PositiveIntegerField(default=0)),
                ("carryover", models.PositiveIntegerField(default=0)),
                ("remaining", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balance_snapshots",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Balance Snapshot",
                "verbose_name_plural": "Leave Balance Snapshots",
                "ordering": ["-snapshot_date", "employee", "leave_type"],
                "indexes": [
                    models.Index(
                        fields=["snapshot_date"], name="core_leaveb_snapsho_fe8ae0_idx"
                    ),
                    models.Index(
                        fields=["employee", "year"],
                        name="core_leaveb_employe_731218_idx",
                    ),
                ],
                "unique_together": {
                    ("employee", "leave_type", "year", "snapshot_date")
                },
            },
        ),
        migrations.CreateModel(
            name="LeaveMonthlyAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("vacation", "Vacation"),
                            ("sick", "Sick Leave"),
                            ("wfh", "Work From Home"),
                            ("personal", "Personal"),
                            ("maternity", "Maternity"),
                            ("paternity", "Paternity"),
                            ("bereavement", "Bereavement"),
                            ("unpaid", "Unpaid Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                ("year", models.PositiveIntegerField(help_text="Calendar year")),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        help_text="Calendar month (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "approved_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Working days from approved leaves in this bucket",
                    ),
                ),
                (
                    "pending_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Working days from pending leaves in this bucket",
                    ),
                ),
                (
                    "rejected_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Working days from rejected leaves in this bucket",
                    ),
                ),
                (
                    "cancelled_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Working days from cancelled leaves in this bucket",
                    ),
                ),
                (
                    "requests_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of distinct LeaveRequest rows contributing to this bucket",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_monthly_aggregates",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Monthly Aggregate",
                "verbose_name_plural": "Leave Monthly Aggregates",
                "ordering": ["-year", "-month", "employee", "leave_type"],
                "indexes": [
                    models.Index(
                        fields=["year", "month"], name="core_leavem_year_1b5de1_idx"
                    ),
                    models.Index(
                        fields=["leave_type", "year", "month"],
                        name="core_leavem_leave_t_57f1b3_idx",
                    ),
                    models.Index(
                        fields=["employee", "year"],
                        name="core_leavem_employe_64df6a_idx",
                    ),
                ],
                "unique_together": {("employee", "leave_type", "year", "month")},
            },
        ),
    ]
