# Generated by Codex on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_alter_timeimportbatch_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeentry",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name="timeentry",
            options={
                "ordering": ["-work_date", "start_time", "employee_id", "project_id"],
                "verbose_name": "Time Entry",
                "verbose_name_plural": "Time Entries",
            },
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["employee", "work_date", "start_time"],
                name="core_timeen_employe_b41c0a_idx",
            ),
        ),
    ]
