# Generated by Django 6.0.3 on 2026-05-26 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_payrollsnapshot_bonusrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompensationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf_level", models.CharField(max_length=100, unique=True)),
                ("net_monthly", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="BAM", max_length=3)),
                ("effective_date", models.DateField()),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comp_policies_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Compensation Policy",
                "verbose_name_plural": "Compensation Policies",
                "ordering": ["cpf_level"],
            },
        ),
        migrations.CreateModel(
            name="BenefitCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "benefit_type",
                    models.CharField(
                        choices=[
                            ("transport", "Transport allowance"),
                            ("meal", "Meal allowance"),
                            ("recreation", "Recreation"),
                            ("health", "Private health"),
                            ("education", "Education stipend"),
                            ("equipment", "Equipment allowance"),
                            ("remote_work", "Remote-work stipend"),
                            ("phone", "Phone / data"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "monthly_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("currency", models.CharField(default="BAM", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("effective_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="benefit_catalog_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Benefit (Catalog)",
                "verbose_name_plural": "Benefits Catalog",
                "ordering": ["benefit_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["benefit_type"], name="core_benefi_benefit_e25336_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="core_benefi_is_acti_8e5dbf_idx"
                    ),
                ],
            },
        ),
    ]
