# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_timeentry_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeentry",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
