# Generated by Django 6.0.3 on 2026-05-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_merge_20260525_1546"),
        ("core", "0057_timeentry_end_time"),
    ]

    operations = []
