# Generated by Django 6.0.3 on 2026-05-26 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_application_decision_fields"),
        ("core", "0058_merge_20260526_0954"),
    ]

    operations = []
