# Generated by Codex on 2026-05-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_merge_20260526_0954"),
        ("core", "0055_application_decision_fields"),
        ("core", "0056_compensationpolicy_benefitcatalog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=160)),
                ("state", models.JSONField(blank=True, default=dict)),
                ("pending_confirmation", models.JSONField(blank=True, default=dict)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Chat Session",
                "verbose_name_plural": "AI Chat Sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AIChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                            ("tool", "Tool"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.aichatsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Chat Message",
                "verbose_name_plural": "AI Chat Messages",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="AIToolCallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool_name", models.CharField(max_length=120)),
                ("arguments", models.JSONField(blank=True, default=dict)),
                ("result_summary", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("blocked", "Blocked"),
                            ("pending_confirmation", "Pending confirmation"),
                        ],
                        max_length=32,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_calls",
                        to="core.aichatsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tool_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Tool Call Log",
                "verbose_name_plural": "AI Tool Call Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aichatsession",
            index=models.Index(
                fields=["user", "is_archived", "-updated_at"],
                name="core_aichat_user_id_3f777b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aichatmessage",
            index=models.Index(
                fields=["session", "created_at"],
                name="core_aichat_session_8986a0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aitoolcalllog",
            index=models.Index(
                fields=["user", "-created_at"],
                name="core_aitool_user_id_f90ec2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aitoolcalllog",
            index=models.Index(
                fields=["session", "-created_at"],
                name="core_aitool_session_a93df7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aitoolcalllog",
            index=models.Index(
                fields=["tool_name", "status"],
                name="core_aitool_tool_na_f01aad_idx",
            ),
        ),
    ]
