# Generated by Django 6.0.3 on 2026-05-28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_application_decision_fields"),
        ("core", "0058_merge_20260526_0954"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(help_text="Rich text HTML content")),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("general", "General"),
                            ("news", "News"),
                            ("celebration", "Celebration"),
                            ("urgent", "Urgent"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_announcements",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CelebrationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("birthday", "Birthday"),
                            ("anniversary", "Anniversary"),
                            ("custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                ("event_date", models.DateField(db_index=True)),
                ("recurs_annually", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_celebration_events",
                        to="core.userprofile",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="celebration_events",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Celebration Event",
                "verbose_name_plural": "Celebration Events",
                "ordering": ["event_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reaction_type", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="core.announcement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_reactions",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Announcement Reaction",
                "verbose_name_plural": "Announcement Reactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["type", "published_at"], name="core_announ_type_662c7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["author", "published_at"], name="core_announ_author__97b127_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="celebrationevent",
            index=models.Index(
                fields=["event_type", "event_date"],
                name="core_celebr_event_t_a670b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="celebrationevent",
            index=models.Index(
                fields=["employee", "event_type"], name="core_celebr_employe_c1e40b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcementreaction",
            index=models.Index(
                fields=["announcement", "reaction_type"],
                name="core_announ_announc_ebb8d0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="announcementreaction",
            index=models.Index(
                fields=["user", "created_at"], name="core_announ_user_id_f91bba_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="announcementreaction",
            constraint=models.UniqueConstraint(
                fields=("announcement", "user", "reaction_type"),
                name="unique_announcement_user_reaction_type",
            ),
        ),
    ]
