# Generated by Django 6.0.3 on 2026-05-29 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_ai_chat"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aichatmessage",
            new_name="core_aichat_session_5ed922_idx",
            old_name="core_aichat_session_8986a0_idx",
        ),
        migrations.RenameIndex(
            model_name="aichatsession",
            new_name="core_aichat_user_id_3c7f55_idx",
            old_name="core_aichat_user_id_3f777b_idx",
        ),
        migrations.RenameIndex(
            model_name="aitoolcalllog",
            new_name="core_aitool_user_id_1a96d2_idx",
            old_name="core_aitool_user_id_f90ec2_idx",
        ),
        migrations.RenameIndex(
            model_name="aitoolcalllog",
            new_name="core_aitool_session_eac00d_idx",
            old_name="core_aitool_session_a93df7_idx",
        ),
        migrations.RenameIndex(
            model_name="aitoolcalllog",
            new_name="core_aitool_tool_na_112f73_idx",
            old_name="core_aitool_tool_na_f01aad_idx",
        ),
    ]
