# Generated by Codex on 2026-05-27

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


def backfill_weekly_allocation_hours(apps, schema_editor):
    project_assignment = apps.get_model("core", "ProjectAssignment")
    for assignment in project_assignment.objects.all().iterator():
        assignment.weekly_allocation_hours = (
            Decimal("40.00")
            * Decimal(assignment.allocation_percentage or 0)
            / Decimal("100")
        ).quantize(Decimal("0.01"))
        assignment.save(update_fields=["weekly_allocation_hours"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_merge_20260526_2148"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectassignment",
            name="weekly_allocation_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Planned weekly time allotment for this project assignment.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(40),
                ],
            ),
        ),
        migrations.RunPython(
            backfill_weekly_allocation_hours, migrations.RunPython.noop
        ),
    ]
