# Generated by Django 6.0.3 on 2026-05-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_announcements_celebration_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["scheduled_at", "published_at"],
                name="core_announ_schedul_86b006_idx",
            ),
        ),
    ]
