# Generated by Django 6.0.3 on 2026-05-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_add_survey_status"),
        ("core", "0056_compensationpolicy_benefitcatalog"),
        ("core", "0056_leave_analytics"),
        ("core", "0060_projectassignment_weekly_allocation_hours"),
    ]

    operations = []
