# Generated by Django 6.0.3 on 2026-05-29 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_announcementcomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordAnnouncementChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("news", "News"),
                            ("celebration", "Celebration"),
                            ("urgent", "Urgent"),
                        ],
                        max_length=32,
                    ),
                ),
                ("channel_name", models.CharField(max_length=255)),
                ("webhook_url_encrypted", models.TextField(blank=True, default="")),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Discord Announcement Channel",
                "verbose_name_plural": "Discord Announcement Channels",
                "ordering": ["announcement_type", "channel_name"],
                "indexes": [
                    models.Index(
                        fields=["announcement_type", "enabled"],
                        name="core_discor_announc_73dc5c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DiscordAnnouncementDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "discord_message_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discord_deliveries",
                        to="core.announcement",
                    ),
                ),
                (
                    "discord_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="core.discordannouncementchannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord Announcement Delivery",
                "verbose_name_plural": "Discord Announcement Deliveries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "attempt_count"],
                        name="core_discor_status_f3b647_idx",
                    ),
                    models.Index(
                        fields=["announcement", "status"],
                        name="core_discor_announc_e6f4ea_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("announcement", "discord_channel"),
                        name="unique_discord_delivery_per_announcement_channel",
                    )
                ],
            },
        ),
    ]
