# Generated by Django 6.0.3 on 2026-05-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_merge_20260528_1936"),
        ("core", "0065_announcementsettings"),
    ]

    operations = []
