# Generated by Django 6.0.3 on 2026-05-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_merge_20260529_1326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="employment_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("probation", "Probation"),
                    ("on_leave", "On Leave"),
                    ("inactive", "Inactive"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
