# Generated by Django 6.0.3 on 2026-05-29 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_merge_20260529_1606"),
        ("core", "0067_alter_userprofile_employment_status"),
    ]

    operations = []
