# Generated by Django 6.0.3 on 2026-05-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_merge_20260529_2340"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Optional cutoff. Submissions are rejected after this date.",
                null=True,
            ),
        ),
    ]
