# Generated by Django 6.0.3 on 2026-05-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_add_survey_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="required",
            field=models.BooleanField(
                default=True,
                help_text="If true, respondents must provide a non-empty answer.",
            ),
        ),
    ]
