# Generated by Django 6.0.3 on 2026-05-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_add_question_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="forbidden_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users explicitly blocked from seeing or submitting this survey.",
                related_name="forbidden_surveys",
                to="core.userprofile",
            ),
        ),
    ]
