# Generated by Django 6.0.3 on 2026-05-31 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0060_rename_core_aichat_session_8986a0_idx_core_aichat_session_5ed922_idx_and_more",
        ),
        ("core", "0071_add_survey_forbidden_users"),
    ]

    operations = []
