# Generated by Django 6.0.3 on 2026-05-31 19:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_merge_20260531_2110"),
    ]

    operations = [
        migrations.CreateModel(
            name="PulseCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.PositiveSmallIntegerField(
                        help_text="Sentiment from 1 (worst) to 5 (best).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null if submitted anonymously.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pulse_checks",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pulse Check",
                "verbose_name_plural": "Pulse Checks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="core_pulsec_created_de7d6c_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("value__gte", 1), ("value__lte", 5)),
                        name="pulse_check_value_between_1_and_5",
                    )
                ],
            },
        ),
    ]
