# Generated by Django 6.0.3 on 2026-05-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_add_pulse_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="pulsecheck",
            name="category",
            field=models.CharField(
                choices=[
                    ("overall", "Overall Satisfaction"),
                    ("workload", "Workload Balance"),
                    ("management", "Management Support"),
                    ("culture", "Team Culture"),
                ],
                default="overall",
                help_text="Which dimension the rating applies to.",
                max_length=20,
            ),
        ),
    ]
