# Generated by Django 6.0.3 on 2026-06-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_merge_20260531_1226"),
        ("core", "0074_add_pulse_check_category"),
    ]

    operations = []
