# Generated by Django 6.0.3 on 2026-06-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_merge_20260601_1159"),
        ("core", "0075_merge_20260601_1247"),
    ]

    operations = []
