# Generated by Django 6.0.3 on 2026-06-01 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_merge_20260601_1414"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JiraUserConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jira_account_id", models.CharField(max_length=255, unique=True)),
                (
                    "jira_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "jira_display_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("cloud_id", models.CharField(max_length=255)),
                ("site_url", models.URLField()),
                ("access_token_encrypted", models.TextField(blank=True, default="")),
                ("refresh_token_encrypted", models.TextField(blank=True, default="")),
                ("token_expires_at", models.DateTimeField()),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("last_refresh_at", models.DateTimeField(blank=True, null=True)),
                ("last_refresh_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jira_user_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Jira User Connection",
                "verbose_name_plural": "Jira User Connections",
            },
        ),
        migrations.CreateModel(
            name="JiraOAuthState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=128, unique=True)),
                (
                    "redirect_to",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jira_oauth_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Jira OAuth State",
                "verbose_name_plural": "Jira OAuth States",
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="core_jiraoa_created_b82bd4_idx"
                    )
                ],
            },
        ),
    ]
