# Generated by Django 6.0.3 on 2026-06-01 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_add_jira_oauth"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TempoUserConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tempo_account_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "tempo_display_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "tempo_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("base_url", models.URLField(default="https://api.tempo.io/4")),
                ("access_token_encrypted", models.TextField(blank=True, default="")),
                ("refresh_token_encrypted", models.TextField(blank=True, default="")),
                ("token_expires_at", models.DateTimeField()),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("last_refresh_at", models.DateTimeField(blank=True, null=True)),
                ("last_refresh_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tempo_user_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tempo User Connection",
                "verbose_name_plural": "Tempo User Connections",
            },
        ),
        migrations.CreateModel(
            name="TempoOAuthState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=128, unique=True)),
                (
                    "redirect_to",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tempo_oauth_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tempo OAuth State",
                "verbose_name_plural": "Tempo OAuth States",
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="core_tempoo_created_fc961b_idx"
                    )
                ],
            },
        ),
    ]
