# Generated by Django 6.0.3 on 2026-06-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_add_tempo_oauth"),
    ]

    operations = [
        migrations.AddField(
            model_name="jirauserconnection",
            name="last_sync_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="jirauserconnection",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
