# Generated by Codex on 2026-06-02

import datetime
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_add_jira_user_connection_sync_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempoAbsenceSyncSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "default_jira_issue_key",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "leave_type_issue_keys",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "daily_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("8.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "default_start_time",
                    models.TimeField(default=datetime.time(9, 0)),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tempo Absence Sync Settings",
                "verbose_name_plural": "Tempo Absence Sync Settings",
            },
        ),
        migrations.CreateModel(
            name="TempoAbsenceSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField()),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("vacation", "Vacation"),
                            ("sick", "Sick Leave"),
                            ("wfh", "Work From Home"),
                            ("personal", "Personal"),
                            ("maternity", "Maternity"),
                            ("paternity", "Paternity"),
                            ("bereavement", "Bereavement"),
                            ("unpaid", "Unpaid Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "jira_issue_key",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "jira_issue_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "tempo_worklog_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("synced", "Synced"),
                            ("failed", "Failed"),
                            ("deleted", "Deleted"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "error_code",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("payload_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tempo_absence_syncs",
                        to="core.userprofile",
                    ),
                ),
                (
                    "leave_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tempo_absence_syncs",
                        to="core.leaverequest",
                    ),
                ),
                (
                    "time_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tempo_absence_syncs",
                        to="core.timeentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tempo Absence Sync",
                "verbose_name_plural": "Tempo Absence Syncs",
                "ordering": ["-work_date", "leave_request_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="tempoabsencesync",
            constraint=models.UniqueConstraint(
                fields=("leave_request", "work_date"),
                name="unique_tempo_absence_sync_leave_date",
            ),
        ),
        migrations.AddIndex(
            model_name="tempoabsencesync",
            index=models.Index(
                fields=["status", "work_date"],
                name="core_tempoa_status_9d109a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tempoabsencesync",
            index=models.Index(
                fields=["employee", "work_date"],
                name="core_tempoa_employe_aa9a9e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tempoabsencesync",
            index=models.Index(
                fields=["tempo_worklog_id"],
                name="core_tempoa_tempo_w_aaf984_idx",
            ),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("jira", "Jira"),
                    ("tempo", "Tempo"),
                    ("document_import", "Document Import"),
                    ("bloomhub_leave", "BloomHub Leave"),
                ],
                default="manual",
                max_length=30,
            ),
        ),
    ]
